### ISSUE TITLE
[BUG] Panic InitFromSnapshot()

### ISSUE THREAD

**Issue by YuXiaoCoder** [avascriptions/open-indexer#5]
The logs are as follows
```bash
./indexer --snapshot /mnt/ascmain/node/snap-40953600.bin

2024/02/02 10:20:17 global init
time="2024-02-02T10:20:17+08:00" level=info msg="start with empty database"
time="2024-02-02T10:20:17+08:00" level=info msg="start indexer"
panic: assignment to entry in nil map

goroutine 1 [running]:
open-indexer/handlers.InitFromSnapshot()
	/opt/ascmain/core/open-indexer/handlers/snapshot.go:91 +0x913
main.main()
	/opt/ascmain/core/open-indexer/cmd/main.go:21 +0xb2
```

```go
        for idx := range protoSnapshot.Balances {
                userBalances := protoSnapshot.Balances[idx]
                address := utils.BytesToHexStr(userBalances.Address)
                balances[address] = make(map[string]*model.DDecimal)
                for idx2 := range userBalances.Balances {
                        tickBalance := userBalances.Balances[idx2]

                        lowerTick := strings.ToLower(tickBalance.Tick)
                        balance, _, _ := model.NewDecimalFromString(tickBalance.Amount)

                        balances[address][lowerTick] = balance
                        tokenHolders[lowerTick][address] = balance

                        updatedBalances[address+lowerTick] = tickBalance.Amount

                        holderCount++
                }
        }
```

**Comment by avascriptions** [comment]
OK, I'll check.

**Comment by avascriptions** [comment]
This bug has been fixed
